
version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: transfer-backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    container_name: transfer-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
